# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time',
            field=models.DateTimeField(verbose_name='submit_date'),
        ),
    ]
